name: Build and Push Admin Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/admin-new/**'
      - 'packages/api-client/**'
      - 'packages/ui/**'
      - 'docker/Dockerfile.admin'
      - '.github/workflows/admin-docker-build.yml'
  workflow_dispatch:

jobs:
  build-and-push-admin:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Set environment variables
      - name: Set environment variables
        run: |
          # Load API_URL from GitHub secrets
          echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV

      # Build and push Admin image
      - name: Build and push Admin image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.admin
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/admin:latest
            ghcr.io/${{ github.repository }}/admin:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            API_URL=${{ env.API_URL }} 