name: Continuous Deployment (Prod) (Admin)
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/admin-new/**'
      - 'packages/ui/**'
      - 'packages/api-client/**'
      - 'docker/Dockerfile.admin'
      - '.github/workflows/deploy_admin.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - dev

jobs:
  deploy-admin:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Set environment variables
      - name: Set environment variables
        run: |
          # Determine environment
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          fi
          
          # Set image tags based on environment
          ENV="${{ env.ENVIRONMENT }}"
          SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=yashmakhija/kanal-kamara-admin:${ENV}-${SHA_SHORT}" >> $GITHUB_ENV
          echo "IMAGE_LATEST=yashmakhija/kanal-kamara-admin:${ENV}" >> $GITHUB_ENV
          
          # Add latest tag for production
          if [[ "${{ env.ENVIRONMENT }}" == "production" ]]; then
            echo "IMAGE_LATEST_ALSO=yashmakhija/kanal-kamara-admin:latest" >> $GITHUB_ENV
          fi
          
          # Load environment-specific variables from GitHub secrets
          echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
          echo "NODE_ENV=${{ env.ENVIRONMENT }}" >> $GITHUB_ENV
      
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.admin
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_LATEST }}
            ${{ env.IMAGE_LATEST_ALSO }}
          cache-from: type=registry,ref=${{ env.IMAGE_LATEST }}
          cache-to: type=inline
          build-args: |
            API_URL=${{ env.API_URL }}
            NODE_ENV=${{ env.NODE_ENV }}
      
     